### ISSUE TITLE
Alinhar a Aba Transparente do Carrossel Conteúdo Exclusivo

### ISSUE THREAD

**Issue by SamambaMan** [SamambaMan/frontendcbv#18]
A aba transparente do Carrossel do Conteúdo Exclusivo não permanece alinhada a esquerda nas variadas resoluções
Ou então corta.
![image](https://user-images.githubusercontent.com/7691477/27254215-83404312-535a-11e7-970e-6033ad531a5a.png)

![image](https://user-images.githubusercontent.com/7691477/27254218-964669be-535a-11e7-82b7-11797d432758.png)

**Comment by lucianobarauna** [comment]
Add a página com o bug
https://samambaman.github.io/frontendcbv/contExclusivo.html

**Comment by lucianobarauna** [comment]
Bug acertado pull request em: https://github.com/SamambaMan/frontendcbv/pull/19
